
		/// <reference types="cypress" />

		context('Generated By Ctflow', () => {
			it('Demo CtFlow', () => {
				
      cy.visit('https://auth.planetscale.com/sign-up')
    

    cy.get('#user_email').type('hungdh131@gmail.com')
    

    cy.get('#user_password').type('thisIS##@123thepassword')
    

    cy.get('#user_password_confirmation').type('thisIS##@123thepassword')
    

      cy.get('#tos').click()
    

      cy.wait(1500)
    

      cy.get(':nth-child(7) > .btn').click()
    

      cy.get('body').contains("Email is invalid or has already been taken")
    

      cy.get('.text-xl').contains("Sign up")
    

			})
		})
		